// React/src/App.tsx
import React, { useCallback, useState, useMemo } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';

import FileManager, { Permissions } from 'devextreme-react/file-manager';

import { getAmazonFileSystemProvider } from './api/amazon.custom.provider';

const allowedFileExtensions: string[] = [];

export default function App(): JSX.Element {
  const [requests, setRequests] = useState<
  { method: string; urlPath: string; queryString: string }[]
  >([]);
  const onRequestExecuted = useCallback(
    ({
      method,
      urlPath,
      queryString,
    }: {
      method: string;
      urlPath: string;
      queryString: string;
    }): void => {
      const request = { method, urlPath, queryString };
      setRequests((requests) => [request, ...requests]);
    },
    [],
  );
  const fileSystemProvider = useMemo(() => getAmazonFileSystemProvider(
    'https://localhost:52366/api/AmazonS3',
    onRequestExecuted,
  ), []);

  return (
    <div className="main">
      <FileManager
        id="file-manager"
        fileSystemProvider={fileSystemProvider}
        allowedFileExtensions={allowedFileExtensions}
      >
        <Permissions download={true}></Permissions>
        {/* uncomment the code below to enable file/directory management */}
        <Permissions
          create={true}
          copy={true}
          move={true}
          delete={true}
          rename={true}
          upload={true}
          download={true}>
        </Permissions>
      </FileManager>
      <div id="request-panel">
        {requests.map((r, i) => (
          <div key={i} className="request-info">
            <div className="parameter-info">
              <div className="parameter-name">Method:</div>
              <div className="parameter-value dx-theme-accent-as-text-color">
                {r.method}
              </div>
            </div>
            <div className="parameter-info">
              <div className="parameter-name">Url path:</div>
              <div className="parameter-value dx-theme-accent-as-text-color">
                {r.urlPath}
              </div>
            </div>
            <div className="parameter-info">
              <div className="parameter-name">Query string:</div>
              <div className="parameter-value dx-theme-accent-as-text-color">
                {r.queryString}
              </div>
            </div>
            <br />
          </div>
        ))}
      </div>
    </div>
  );
}

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import CustomFileSystemProvider from 'devextreme/file_management/custom_provider';
import { Service } from './services/app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [Service],
})
export class AppComponent {
  allowedFileExtensions: string[];

  fileSystemProvider!: CustomFileSystemProvider;

  requests: any[];

  constructor(service: Service) {
    const endpointUrl = 'https://localhost:7128/api/AmazonS3';
    this.allowedFileExtensions = [];

    this.requests = [];
    this.fileSystemProvider = service.getAmazonFileSystemProvider(endpointUrl, this.onRequestExecuted);
  }

  onRequestExecuted = ({ method, urlPath, queryString }: { method: string; urlPath: string; queryString: string }): void => {
    const request = { method, urlPath, queryString };
    this.requests.unshift(request);
  };
}

<div class="default-style">
  <dx-file-manager
    id="file-manager"
    [fileSystemProvider]="fileSystemProvider"
    [allowedFileExtensions]="allowedFileExtensions"
  >
    <dxo-upload [chunkSize]="6000000"></dxo-upload>
    <!-- uncomment the code below to enable file/directory management -->
    <dxo-permissions
      [create]="true"
      [copy]="true"
      [move]="true"
      [delete]="true"
      [rename]="true"
      [upload]="true"
      [download]="true"
    >
    </dxo-permissions>
  </dx-file-manager>
  <div id="request-panel">
    <div class="request-info" *ngFor="let request of requests">
      <div class="parameter-info">
        <div class="parameter-name">Method:</div>
        <div class="parameter-value dx-theme-accent-as-text-color">{{
          request.method
        }}</div>
      </div>
      <div class="parameter-info">
        <div class="parameter-name">Url path:</div>
        <div class="parameter-value dx-theme-accent-as-text-color">{{
          request.urlPath
        }}</div>
      </div>
      <div class="parameter-info">
        <div class="parameter-name">Query string:</div>
        <div class="parameter-value dx-theme-accent-as-text-color">{{
          request.queryString
        }}</div>
      </div>
      <br />
    </div>
  </div>
</div>
